### ISSUE TITLE
Cropping does not always stick to the aspect ratio

### ISSUE THREAD

**Issue by edvsjo** [edvsjo/photocropper#7]
This is most clearly seen in Only-Carol-Dress_383296_65_extra4.jpg where the product does not overrlap with edges, but still contains too little white space.

**Comment by magnunm** [comment]
Yep, this was just a silly bug! Fixed it in 9f8499d803cf0b8cd405ba66b7eed239d01d5086 :smile: 

Now it has always the correct aspect ratio. But, it still does the padding in a strange way. Seems like it thinks the product is wider than the picture, which it clearly isn't. Will investigate.

**Comment by magnunm** [comment]
Ok have figured out the causes:

First was another simple bug which exchanged columns and rows and therefore placed the center of the product falsely, fixed that here: e37a9cbdd1ceaf25be7c5766bd9ceb8fd5693bdb

After fixing the above, still had the problem that it was aligning the product in the corner even when it did not need to. Fixed so that it only corner-aligns when the product is actually in said corner here: 79b3332c2f76d867e29fa8c3b1510013cacb0f48

It seems to work much better now. Test out the changes (pushed to `master`) and I think you can close this issue if you also agree it is fixed! 😄

**Comment by edvsjo** [comment]
Seems to work as intended. There is still some disparity, but not enough to cause problems for the final cropping of the image. After some testing i got the the follwing aspect ratios:
- 1340/1620 = 0.82716049382
- 2068/2500 = 0.8272
- 1395/1687 = 0.82691167753
- 2036/2462 = 0.82696994313
I think these results are close enough to the actual aspect ratio of 1500/1814 = 0.82690187431 That there will be little to none noticible difference when rescaling the images. So great work in solving this issue!

**Comment by edvsjo** [comment]
Hit the wrong button
